### PR TITLE
Fixed author links

### LINKED ISSUE #247: Author links are being returned wrong in posts page
When the author link is accessed from a post page, it returns the following:

author_issue

### PR DESCRIPTION
**Pull request by chandonn-zz**
Fixes #247

### CODE REVIEW

File: includes/class-monk-links.php [hunk 1]
```diff
@@ -499,9 +499,7 @@ public function monk_add_language_author_permalink( $link, $author_id ) {
 		$default_language_url = get_option( 'monk_default_language_url', false );
 		$language             = ( get_query_var( 'lang' ) ) ? get_query_var( 'lang' ) : $this->site_language;
 
-		if ( $this->monk_using_permalinks() ) {
```
Comment (chandonn) [inline includes/class-monk-links.php]: Since the changes we have made in the home_url() returning value, there is no need to change with the permalinks active

File: includes/class-monk-links.php [hunk 2]
```diff
@@ -499,9 +499,7 @@ public function monk_add_language_author_permalink( $link, $author_id ) {
...
-			$link = $default_language_url || $language !== $default_slug ? str_replace( $this->site_home . '/' . $this->site_root, $this->site_home . '/' . $this->site_root . $language . '/', $link ) : $link;
-		} else {
+		if ( ! $this->monk_using_permalinks() ) {
```
Comment (brenoalvs) [inline includes/class-monk-links.php:502]: This solves the error for every permalink structure?

Comment (chandonn-zz) [reply includes/class-monk-links.php:502]: Yes it does, a have tested. The author links does not changes with permalinks, it comes the same:
example.com/en/author-name

**Review by brenoalvs — APPROVED** [review]
